package app.historycompare;

public enum AttributionEffect {
    INTRODUCES_STATE_DIFFERENCE,
    INTRODUCES_ACTION_DIFFERENCE,
    INTRODUCES_STATE_AND_ACTION_DIFFERENCE,
    REPAIRS_STATE_DIFFERENCE,
    REPAIRS_ACTION_DIFFERENCE,
    REPAIRS_STATE_AND_ACTION_DIFFERENCE,
    PRESERVES_DIFFERENCE,
    NO_SEMANTIC_CHANGE
}
